inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/*'
    - 'spec/*'

Airbnb/OptArgParameters:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Airbnb/DefaultScope:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
